[project]
name = "st-pdf-foundry"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pillow>=11.3.0",
    "pymupdf>=1.26.3",
    "pypdf>=6.0.0",
    "streamlit>=1.48.1",
]
